AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bundle/**/*'

Documentation:
  Enabled: false
AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  EnforcedStyle: hash_rockets
MethodLength:
  Enabled: false
LineLength:
  Max: 200
Style/FileName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false